#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

runApplication blockMesh 
runApplication pimpleFoam
runApplication foamToVTK //to view VTK files in paraview


runApplication $application

#------------------------------------------------------------------------------
